feat: add refund support
TransbankDevelopers/transbank-plugin-magento2-webpay-rest pull request #82
Opened 2024-03-26 12:58 UTC by Matiasnickolas

This PR add support for refunds on Webpay Plus and Oneclick.

![image](https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay-rest/assets/101830551/9aca2564-31d0-41aa-b720-e23872f3be11)

Reverse: 
![image](https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay-rest/assets/101830551/a169f0da-2d60-4c20-93ee-cbd75397cd82)

![image](https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay-rest/assets/101830551/e90537ab-2d43-48f4-ac08-170daf0348d2)

Partial refund:
![image](https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay-rest/assets/101830551/4c8173bd-fb2d-429f-b3d1-eb8369240bf3)

![image](https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay-rest/assets/101830551/d6f2866d-d634-4d5d-ad26-ddd366fd35d3)

2024-03-26 13:04 UTC, tribiec submitted a review, later dismissed
GJ 🚀

2024-03-26 15:30 UTC, victormendoza96 approved these changes, later dismissed

2024-03-26 17:27 UTC, mastudillot requested changes
add format to date field

2024-03-27 14:42 UTC, mastudillot approved these changes
LGTM

2024-03-27 14:48 UTC, victormendoza96 approved these changes

2024-03-27 14:48 UTC, merged